// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/cage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CageService_StartWithdraw_FullMethodName = "/proto.CageService/StartWithdraw"
)

// CageServiceClient is the client API for CageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CageService defines the gRPC service for managing withdrawals via the Cage component.
type CageServiceClient interface {
	// StartWithdraw initiates a withdrawal request on the blockchain.
	// It corresponds to the 'startWithdraw' function in the ICustody contract.
	StartWithdraw(ctx context.Context, in *StartWithdrawRequest, opts ...grpc.CallOption) (*StartWithdrawResponse, error)
}

type cageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCageServiceClient(cc grpc.ClientConnInterface) CageServiceClient {
	return &cageServiceClient{cc}
}

func (c *cageServiceClient) StartWithdraw(ctx context.Context, in *StartWithdrawRequest, opts ...grpc.CallOption) (*StartWithdrawResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWithdrawResponse)
	err := c.cc.Invoke(ctx, CageService_StartWithdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CageServiceServer is the server API for CageService service.
// All implementations must embed UnimplementedCageServiceServer
// for forward compatibility.
//
// CageService defines the gRPC service for managing withdrawals via the Cage component.
type CageServiceServer interface {
	// StartWithdraw initiates a withdrawal request on the blockchain.
	// It corresponds to the 'startWithdraw' function in the ICustody contract.
	StartWithdraw(context.Context, *StartWithdrawRequest) (*StartWithdrawResponse, error)
	mustEmbedUnimplementedCageServiceServer()
}

// UnimplementedCageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCageServiceServer struct{}

func (UnimplementedCageServiceServer) StartWithdraw(context.Context, *StartWithdrawRequest) (*StartWithdrawResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWithdraw not implemented")
}
func (UnimplementedCageServiceServer) mustEmbedUnimplementedCageServiceServer() {}
func (UnimplementedCageServiceServer) testEmbeddedByValue()                     {}

// UnsafeCageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CageServiceServer will
// result in compilation errors.
type UnsafeCageServiceServer interface {
	mustEmbedUnimplementedCageServiceServer()
}

func RegisterCageServiceServer(s grpc.ServiceRegistrar, srv CageServiceServer) {
	// If the following call panics, it indicates UnimplementedCageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CageService_ServiceDesc, srv)
}

func _CageService_StartWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CageServiceServer).StartWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CageService_StartWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CageServiceServer).StartWithdraw(ctx, req.(*StartWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CageService_ServiceDesc is the grpc.ServiceDesc for CageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CageService",
	HandlerType: (*CageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWithdraw",
			Handler:    _CageService_StartWithdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cage.proto",
}
