// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/cage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StartWithdrawRequest contains the parameters required to start a withdrawal.
type StartWithdrawRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address of the user initiating the withdrawal (hex string).
	UserAddress string `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	// The address of the token being withdrawn (hex string). Use address(0) for native ETH.
	TokenAddress string `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	// The amount to withdraw (string representation of uint256).
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// A unique nonce to prevent replay attacks (string representation of uint256).
	Nonce         string `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWithdrawRequest) Reset() {
	*x = StartWithdrawRequest{}
	mi := &file_proto_cage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWithdrawRequest) ProtoMessage() {}

func (x *StartWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWithdrawRequest.ProtoReflect.Descriptor instead.
func (*StartWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_cage_proto_rawDescGZIP(), []int{0}
}

func (x *StartWithdrawRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *StartWithdrawRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *StartWithdrawRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *StartWithdrawRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// StartWithdrawResponse returns the result of the withdrawal initiation.
type StartWithdrawResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the withdrawal generated by the contract (hex string).
	WithdrawalId string `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	// The transaction hash of the initiated withdrawal (hex string).
	TxHash        string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWithdrawResponse) Reset() {
	*x = StartWithdrawResponse{}
	mi := &file_proto_cage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWithdrawResponse) ProtoMessage() {}

func (x *StartWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWithdrawResponse.ProtoReflect.Descriptor instead.
func (*StartWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_cage_proto_rawDescGZIP(), []int{1}
}

func (x *StartWithdrawResponse) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

func (x *StartWithdrawResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_proto_cage_proto protoreflect.FileDescriptor

const file_proto_cage_proto_rawDesc = "" +
	"\n" +
	"\x10proto/cage.proto\x12\x05proto\"\x8c\x01\n" +
	"\x14StartWithdrawRequest\x12!\n" +
	"\fuser_address\x18\x01 \x01(\tR\vuserAddress\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\"U\n" +
	"\x15StartWithdrawResponse\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash2Y\n" +
	"\vCageService\x12J\n" +
	"\rStartWithdraw\x12\x1b.proto.StartWithdrawRequest\x1a\x1c.proto.StartWithdrawResponseB$Z\"github.com/layer-3/nitewatch/protob\x06proto3"

var (
	file_proto_cage_proto_rawDescOnce sync.Once
	file_proto_cage_proto_rawDescData []byte
)

func file_proto_cage_proto_rawDescGZIP() []byte {
	file_proto_cage_proto_rawDescOnce.Do(func() {
		file_proto_cage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cage_proto_rawDesc), len(file_proto_cage_proto_rawDesc)))
	})
	return file_proto_cage_proto_rawDescData
}

var file_proto_cage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cage_proto_goTypes = []any{
	(*StartWithdrawRequest)(nil),  // 0: proto.StartWithdrawRequest
	(*StartWithdrawResponse)(nil), // 1: proto.StartWithdrawResponse
}
var file_proto_cage_proto_depIdxs = []int32{
	0, // 0: proto.CageService.StartWithdraw:input_type -> proto.StartWithdrawRequest
	1, // 1: proto.CageService.StartWithdraw:output_type -> proto.StartWithdrawResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cage_proto_init() }
func file_proto_cage_proto_init() {
	if File_proto_cage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cage_proto_rawDesc), len(file_proto_cage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cage_proto_goTypes,
		DependencyIndexes: file_proto_cage_proto_depIdxs,
		MessageInfos:      file_proto_cage_proto_msgTypes,
	}.Build()
	File_proto_cage_proto = out.File
	file_proto_cage_proto_goTypes = nil
	file_proto_cage_proto_depIdxs = nil
}
